// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIA6KBOtYYqdsch1-ZOcA-GLhcdRPK7LU',
    appId: '1:459693191054:web:a89f118eaf7bb572dfbedf',
    messagingSenderId: '459693191054',
    projectId: 'ayadi-49020',
    authDomain: 'ayadi-49020.firebaseapp.com',
    storageBucket: 'ayadi-49020.appspot.com',
    measurementId: 'G-2EL6KFYEKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArmfZ7qbpT4exlF8nAt5G9Ebv1yxJw4OI',
    appId: '1:459693191054:android:26a3678b7baa235ddfbedf',
    messagingSenderId: '459693191054',
    projectId: 'ayadi-49020',
    storageBucket: 'ayadi-49020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKauMaYzJ5Sd2-L5gpWeihpxNuJYXvMaM',
    appId: '1:459693191054:ios:6f13eb17957e95bcdfbedf',
    messagingSenderId: '459693191054',
    projectId: 'ayadi-49020',
    storageBucket: 'ayadi-49020.appspot.com',
    iosClientId: '459693191054-5rm2s7sdnttmatobmi6vkdmh1668i6t2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKauMaYzJ5Sd2-L5gpWeihpxNuJYXvMaM',
    appId: '1:459693191054:ios:6f13eb17957e95bcdfbedf',
    messagingSenderId: '459693191054',
    projectId: 'ayadi-49020',
    storageBucket: 'ayadi-49020.appspot.com',
    iosClientId: '459693191054-5rm2s7sdnttmatobmi6vkdmh1668i6t2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayadi',
  );
}
